### ISSUE TITLE
Converter tópico 'Política de qualificação' do PPC

### ISSUE THREAD

**Issue by pedlop** [pedlop/integracao2017#15]
Realizar a Conversão do tópico 'Política de qualificação' do PPC, que se inicia na página 29, para o formato JSON definido.
- **Observação:** para realizar a conversão, solicitar o texto, convertido da imagem disponibilizada do PPC, para mim, @pedlop... será definido o local de armazenamento para este texto posteriormente.

**Comment by igorqsilva** [comment]
Adicionado e validado através do https://jsonformatter.org/
