### ISSUE TITLE
Adicionar chave_especial

### ISSUE THREAD

**Issue by pedlop** [pedlop/integracao2017#22]
Adicionar a chave_especial para todos os objetos primarios no arquivo json, esta chave é um Array e será composta por palavras "chave" de cada texto, poderá ser filtrada no momento da pesquisa.
* **Observação:** Esta chave só será criada após a conclusão do arquivo json.
  * No Array, cada posição será composta por apenas 1 (uma) palavra.

**Comment by igorqsilva** [comment]
Chaves adicionadas
