### ISSUE TITLE
Criar modelo da Terceira Camada e apresentar para os demais membros

### ISSUE THREAD

**Issue by pedlop** [pedlop/integracao2017#3]
Quem desejar criar um protótipo, demonstrando como vislumbra o template da terceira camada (Camada de detalhamento do Curso), poderá realizar a construção e deverá apresentar para os demais membros, na aula subsequente da disciplina.

**Comment by marcosvsilva** [comment]
Modelo criado e apresentado no grupo de WhatsApp da disciplina

**Comment by marcosvsilva** [comment]
[ProtótipoDeIdeiaDaPrimeiraCamada](https://drive.google.com/file/d/0B--rxe6RDUfpVnZmVjhvNTI2Rk0/view)

**Comment by marcosvsilva** [comment]
Finalizada.
