### ISSUE TITLE
Converter tópico 'Expectativa da formação do profissional' do PPC

### ISSUE THREAD

**Issue by pedlop** [pedlop/integracao2017#7]
Realizar a Conversão do tópico 'Contexto' do PPC, que se inicia na página 15, para o formato JSON definido.
- **Observação:** para realizar a conversão, solicitar o texto, convertido da imagem disponibilizada do PPC, para mim, @pedlop... será definido o local de armazenamento para este texto posteriormente.

**Comment by marcosvsilva** [comment]
Finalizada
