### ISSUE TITLE
Converter tópico 'Princípios norteadores' do PPC

### ISSUE THREAD

**Issue by pedlop** [pedlop/integracao2017#8]
Realizar a Conversão do tópico 'Contexto' do PPC, que se inicia na página 18, para o formato JSON definido.
- **Observação:** para realizar a conversão, solicitar o texto, convertido da imagem disponibilizada do PPC, para mim, @pedlop... será definido o local de armazenamento para este texto posteriormente.

**Comment by joaohhenriq** [comment]
Falta adicionar a foto presente nessa categoria.
